version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "appa/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Download Ruby Dependencies
          command: bundle check || bundle install --path vendor/bundle

      - run:
          name: Build
#          command: bundle exec fastlane test_lint
          command: ./gradlew build


